# Generated by Django 6.0.3 

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('health', 'Здоровье'), ('sport', 'Спорт'), ('study', 'Учеба'), ('hobby', 'Хобби'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('how_often', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=20, verbose_name='Частота')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('done', models.BooleanField(default=True, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.habit')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журнала',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
