# Generated by Django 6.0.3 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, verbose_name='Дни недели'),
        ),
    ]
