# Generated by Django 6.0.3 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habit_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Приостановлена'),
        ),
        migrations.AddField(
            model_name='habit',
            name='pause_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец паузы'),
        ),
        migrations.AddField(
            model_name='habit',
            name='pause_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало паузы'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить напоминания'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время напоминания'),
        ),
    ]
