# Generated by Django 6.0.3 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_habit_is_paused_habit_pause_end_habit_pause_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для уведомлений'),
        ),
    ]
