# Generated by Django 6.0.3 

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(verbose_name='Дата отправки')),
                ('sent_time', models.TimeField(verbose_name='Время отправки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='tracker.habit')),
            ],
            options={
                'verbose_name': 'Лог напоминаний',
                'verbose_name_plural': 'Логи напоминаний',
                'ordering': ['-created'],
            },
        ),
    ]
